### PR TITLE
generic.transfer: support single file max_concurrency

### PR DESCRIPTION
**Pull request by pmrowla**
For filesystems that support `max_concurrency` within single file transfers (currently only adlfs), generic transfer methods now behave the same as fsspec batched put/get. When transferring a single file we set `max_concurrency=jobs`. When transferring more than one file we set `batch_size=jobs` and `max_concurrency=1`.

This implementation is naive and could be optimized further in the future (by actually balancing concurrent files and concurrent chunks within files), but for now this handles the worst-case scenario for these filesystems (single file upload/download)

Closes https://github.com/iterative/dvc-azure/issues/54

### CODE REVIEW

**Comment by pmrowla** [comment]
> It feels a bit wrong to introduce fs-specific kwargs on something that is supposed to be fs-agnostic.

`max_concurrency` is currently only supported in adlfs, but it will probably be worthwhile for us to submit similar patches for s3fs and gcfs (and exposing concurrency for chunked upload/download as a general fsspec API feature in the same way that `batch_size` is exposed).

**Comment by pmrowla** [comment]
The adlfs patch does already include overridden behavior for fsspec `get()` and `put()` batching, which has the same naive behavior we do here, where it's either `max_concurrency=batch_size` for a single file transfer, or `max_concurrency=1`+`batch_size=batch_size` for batched file transfers.

Since we don't use fsspec `put()`/`get()` in `generic.transfer` we have to do the same thing here.

**Comment by shcheklein** [comment]
thanks @pmrowla ! Folks, why not keep both options enabled simultaneously? e.g. batch_size=jobs and max_concurrency=<some default> . And let people control it via `-j` if they run into a problem. This way there will a workaround, but in the current implementation the only way to speedup is to run `dvc pull` file by file? can be tricky a bit ... and it can be confusing that two files become drastically slower ...

**Comment by pmrowla** [comment]
@shcheklein in that case our concurrency level will be `jobs * jobs`, which is generally going to be way too high in the default case. I also considered splitting `jobs` between the two (so `batch_size=(min(1, jobs // 2))` and the same for `max_concurrency`) but that will make us perform a lot worse in the cases where you are pushing a large # of files that are smaller than the chunk size

I think it will be worth revisiting this and handling it properly and actually determining what level of concurrency we should be using at both the file and chunk level, but that is dependent on the number of files being transferred, the size of all of those files, and the chunk size for the given cloud. This is all work that we can do at some point, but in the short term I prioritized getting a fix for the worst case scenario for azure (pushing a single large file).

Also, any work that we do on this right now would only work for Azure, since right now adlfs is the only underlying fsspec implementation that actually does concurrent chunked/multipart upload/downloads . It would be better for us to contribute upstream to make the s3/gcs/etc implementations support the chunk/multipart concurrency first, before we get into trying to make DVC optimize balancing file and chunk level concurrency

**Comment by dberenbaum** [comment]
> It would be better for us to contribute upstream to make the s3/gcs/etc implementations support the chunk/multipart concurrency first, before we get into trying to make DVC optimize balancing file and chunk level concurrency

Agree here. Until we can do more, we can at least tell people to pull a large file individually if it's too slow. Since file-level concurrency is the baseline we have established, we should err on the side of not making those scenarios slower.

What does `batch_size` mean here/in fsspec? Seems odd that `batch_size=jobs`. I thought of `batch_size` as size of data in a single request/thread and jobs as number of concurrent requests/threads.

**Comment by pmrowla** [comment]
> What does batch_size mean here/in fsspec? Seems odd that batch_size=jobs. I thought of batch_size as size of data in a single request/thread and jobs as number of concurrent requests/threads.

fsspec `batch_size` is equivalent to DVC jobs. fsspec schedules asyncio coroutines in batches, and `batch_size` is the number of coroutines it will try to run at a time (so it equates to the number of concurrent requests that fsspec can make at once).

**Comment by pmrowla** [comment]
@dberenbaum yes, that's what we would want to do eventually. The issue is that the fsspec API is not really set up to do that right now. We can't change `batch_size` on the fly, so right now we would only be able to do it in cases where all of the files we want to transfer are roughly the same size (so there is a consistent number of chunks per file)

**Comment by dberenbaum** [comment]
> It would be better for us to contribute upstream to make the s3/gcs/etc implementations support the chunk/multipart concurrency first, before we get into trying to make DVC optimize balancing file and chunk level concurrency

Do we have an issue to track this?

**Pull request merged**
