### PR TITLE
DVC Custom Filesystem plugins

### LINKED ISSUE #174: DVC FileSystem Plugin
My organisation uses a custom SMB file system solution for the cache and remote storage. 

Mountpoints vary between users, so our current solution is to use local configs i.e. have each user run:
```
dvc remote add -d storage $HOME/path/to/dvc-store --local
dvc remote add -d storage $HOME/path/to/dvc-cache --local
```
to configure their cache and remote. There is a default remote path stored in the Git repository, but this is only used for Docker deployments.

This works great for most of our use cases. The only scenario that we can't currently see a solution to is when using DVC as a data registry. In particular, `dvc get` uses the default remote stored in the repository, which users don't have access to.

One solution to this problem would be to allow custom protocols discovered using plugins. This idea is inspired by the drive artifact repository plugins used by MLFlow: https://www.mlflow.org/docs/latest/plugins.html#aliyun-alibaba-cloud-oss-plugin.

This would enable us to implement our own custom backend, so that URLs could be specified in the form:
```
['remote "storage"']
    url = mycustomprotocol://path/using/protocol
```
where `mycustomprotocol` is resolved using a custom FileSystem subclass from a plugin that is discovered by DVC at runtime. For example, using the Registry class:
https://github.com/iterative/dvc-objects/blob/a1f8c64f584b78eb1c392b1d129b27ca76811b0a/src/dvc_objects/fs/__init__.py#L90

### PR DESCRIPTION
**Pull request by joncarter1**
### Why is this PR useful?
Currently, FileSystem plugins e.g. dvc-azure, dvc-drive, must be explicitly supported within the dvc and dvc-objects repositories.

This PR* would enable users to implement FileSystem plugins _entirely independently_ of DVC.
This would allow users to integrate DVC with custom storage solutions within their organisations without requiring them to be explicitly supported. Popular OSS plugins developed in this way could of course still be added under [known_implementations](https://github.com/joncarter1/dvc-objects/blob/6fb7cac5af6290997dbadc85c269555a0a3f6c66/src/dvc_objects/fs/__init__.py#L18) to improve their visibility.

### What this PR does
This PR allows FileSystem plugins to be discovered using the `DVC_FS_PLUGINS` environment variable.

For example:
```
export DVC_FS_PLUGINS='{"home": {"class":"fs_plugin_examples.HomeFS"}}'
```
with the simple examples found here:
https://github.com/joncarter1/dvc-example-fs-plugin

### To-do
Before I tidy up/write some tests for this, @efiop could you let me know what you think of this idea? :) 
This would be very useful for my organisation, enabling me to develop a custom implementation that works seamlessly across our platform e.g. from user machines to Docker containers.

(* + a small additional backwards-compatible PR on the main DVC repository: https://github.com/iterative/dvc/compare/main...joncarter1:dvc:filesystem-plugin )

n.b. plugin style follows a similar pattern to that seen in libraries such as Ray (https://github.com/ray-project/ray/blob/c38a3cff2398863bf42914d9da50b949b2165de3/python/ray/_private/runtime_env/constants.py#L6 ) 

Closes #174

### CODE REVIEW

**Comment by efiop** [comment]
Hey @joncarter1 !

Thanks for your interest and your effort! 🙏 

The plugins are in the secondary plans for a long time now and we admittedly don't really provide much visibility into the next steps 🙁 

We are still lacking some functionality for the current state (e.g. plugin config options are still all in dvc) and after those are done, we will be ready to introduce a proper registering mechanism. The approach in this PR seems to be purely env-var based, which I don't think will work well for us being so manual 🙁 We've been actually thinking about using something like https://pypi.org/project/pluggy/ instead (Kudos @skshetry ), but we are not ready for that yet and neither are we sure when we will prioritize working on that again.

Btw, do you have some specific need/use-case for writing and using a new plugin?

**Comment by joncarter1** [comment]
Hey @efiop,

I was previously unaware of pluggy but that looks like a great way to go about solving this problem!

#### Example use-case
My specific use-case is using an SMB file system as a remote store, whose local mount point varies between users.
I would like to create a plugin: `smb://host/path/to/store` which will automatically handle finding the mount point for the user. This would only require a simple sub-classing of the existing `LocalFileSystem` class.

This would have a number of benefits:
1. It means the user doesn't have to maintain a local config, they can all use the same remote location specified under version control in the main `.dvc/config` i.e. no need for each user to run a command like `dvc remote add -d storage $HOME/path/to/mountpoint --local` for local development.
2. Simplifies things in deployed Docker containers, since they which will also have a different mountpoint to users.
3. Finally, it would mean `dvc get` works properly our set-up. Currently it does not because that command must use the default remote. But in our set-up, there is no default remote, because the mount-point is different for every user. The plugin I've described above would fix this and let us properly use DVC as a cross-project dataset registry!

I hope that makes sense!

#### Next steps
I would be very happy to convert my implementation to using a mechanism like `pluggy`. I did do some initial experiments with namespace packages, but opted for an env-based approach to quickly get a working PR and initiate a better discussion :smile:.

The naming convention for the filesystem plugins could be something like `dvc-fs-*` ? e.g. `dvc-fs-smb` for my example.

As you can see here:
https://github.com/iterative/dvc/compare/main...joncarter1:dvc:filesystem-plugin
getting a stable alpha version working with the main `dvc` repository may only take a handful of lines of code. It doesn't necessarily have to wait for the refactoring of the config options.

Like I said, I'd be very happy to make this happen but equally I understand if you'd rather I dropped it for now.
Just let me know :smile:

**Comment by efiop** [comment]
@joncarter1 How do you plan on automatically detecting where the mount point is locally?

**Comment by joncarter1** [comment]
@efiop we have functions that use `psutil.disk_partitions` to find local mount points for remote SMB paths within our organisation.

Correct, cross-platform compatibility is not a concern for me right now.

**Comment by efiop** [comment]
@joncarter1 I see, so you have a very very niche use case with some serious assumptions. Makes sense. You could however monkeypatch it for now instead of going the official plugin route. Unless you are already doing that. Just trying to see if we could save you time.

**Comment by joncarter1** [comment]
@efiop correct, this isn’t a plug-in I’d expect anyone outside my organisation to use! (Would be hosted on our internal pypi)

However, I’m sure I won’t be the last person with a niche use-case/storage set-up which would benefit from a custom plugin capability.

I can indeed monkeypatch around it for now but as I said, I’d be more than happy to contribute to this feature - DVC has been such a massive help with my work so far.

If it’s going to interfere with other ongoing work you have then no worries, please feel free to drop me a line in the coming weeks/months and I’d be happy to help out then.

**Comment by efiop** [comment]
@joncarter1 Just making sure you are not really blocked by this 🙂 If you are still keen on contributing a pluggy-based implementation - we would be happy to see it as well 🙏

**Comment by joncarter1** [comment]
@efiop I've switched to a lightweight entrypoint-based implementation using the `importlib_metadata` library.

This provides more flexibility in the naming convention for entry-point discovery than pluggy with a little less boilerplate.
It's very similar to the approach taken by MLFlow Plugins.

Custom plugins now only require a pip install of the custom package.
An example `setup.py` for such a package can be found here:
https://github.com/joncarter1/dvc-fs-example-plugin/blob/main/src/setup.py

Keen to hear what you think! :smile:

**Pull request closed without merging**
