### PR TITLE
fs: http: disable PUT/POST retries

### PR DESCRIPTION
**Pull request by pmrowla**
see https://github.com/iterative/dvc/issues/8100

### CODE REVIEW

**Comment by skshetry** [comment]
I am more inclined on getting rid of `RetryClient`, `aiohttp.TCPConnector` kwarg, upload_method attribute, etc. that we added here instead of upstreaming it and adding complexity.

**Comment by pmrowla** [comment]
I'd be fine with dropping aiohttp_retry entirely as the immediate fix for iterative/dvc#8100, but moving everything else upstream should be opened as a separate issue that can be addressed later

**Review by efiop — APPROVED** [review]

**Comment by efiop** [comment]
Thank you, @pmrowla ! 🙏

**Comment by efiop** [comment]
@pmrowla @skshetry So how do you want to proceed with this long term? Upstreaming to fsspec somehow or something else?

**Comment by simonlsk** [comment]
Hey, having retries doesn't sound like a bad idea to me in general, except when they are causing unintended issues. Does that mean that you are dropping completely retrying failed http post/put requests? Is there an open issue for adding retries "somehow" (not necessarily using `aiohttp_retry.RetryClient`) ?
Sounds like a serious bug on their end, and like something they should fix anyway no?

**Comment by skshetry** [comment]
> Hey, having retries doesn't sound like a bad idea to me in general, except when they are causing unintended issues. Does that mean that you are dropping completely retrying failed http post/put requests? Is there an open issue for adding retries "somehow" (not necessarily using `aiohttp_retry.RetryClient`) ? Sounds like a serious bug on their end, and like something they should fix anyway no?

`POST` is not idempotent. So we cannot retry the request with aiohttp_retry. We have to do so on the filesystem level (and even then it may not always be possible to retry for non-seekable file objects). For some servers, we may need to remove those file before retrying as they may have saved partial content.

The retrying concept is not in fsspec's HTTPFileSystem, we were doing it in dvc itself with `RetryClient` which won't be sufficient. So we need to add support for retrying in fsspec HTTPFileSystem itself. Also for DVC local use case, users can do `dvc push` again which should continue uploading from where it failed.

So, the fix should be in fsspec, by adding retries instead of in DVC.

**Comment by simonlsk** [comment]
Ok, thanks for the response! 
I still don't really understand what's the course of action taken?
What happens in the case PUT or DELETE is available, it sounds like that should be solvable, and prevent the initial `dvc push` command from returning an error when a single retry is successful. 
I'm not very familiar with the fsspec project, do you mean we should open an issue there about that?

**Comment by pmrowla** [comment]
Either proper retry support needs to be added natively in the fsspec HTTP filesystem implementation: https://github.com/fsspec/filesystem_spec/blob/master/fsspec/implementations/http.py
Or the aiohttp-retry behavior for POST operations needs to be fixed: https://github.com/inyutin/aiohttp_retry

We are not currently planning on contributing either fix, but if either of these changes was made upstream we could re-enable PUT/POST retry support in DVC.

Basically this is not something we have the bandwidth to prioritize right now, especially since PUT/POST retry support was already disabled before we switched to the fsspec HTTP implementation (due to the requests/urllib3 retry behavior defaulting to only retry on read HTTP methods). When we switched to using fsspec's HTTP filesystem, we should not have enabled retries for these methods in the first place (due to the aiohttp-retry issues which are now more apparent).

**Pull request merged**
